### ISSUE TITLE
Add YAMLScript track maintainers

### ISSUE THREAD

**Issue by ingydotnet** [exercism/yamlscript#21]
@exercism/staff ,

Please add @vendethiel (https://exercism.org/profiles/vendethiel) as a YAMLScript track maintainer.

**Comment by ErikSchierboom** [comment]
@vendethiel You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)

**Comment by ingydotnet** [comment]
@ErikSchierboom can you also add @m-dango (https://forum.exercism.org/u/m-dango)?

**Comment by ErikSchierboom** [comment]
Done!
